Output split-editors.gif
Set FontSize 16

Hide
Type "go build -o split-editors ."
Enter
Type "clear"
Enter
Show

Type "./split-editors"
Enter
Sleep 2

Type "Hello, there!"
Sleep 1
Tab
Sleep 1
Type "Hi!"
Sleep 1
Enter
Type "How are you?"
Sleep 1
Tab
Sleep 1
Ctrl+U
Sleep 1
Type "I'm good! Thanks for asking :)"
Sleep .5
Enter
Sleep 1
Ctrl+N
Sleep 1
Tab@.5 2
Type "Hello, world!"
Sleep 2

Hide
Escape
Type "rm split-editors"
Enter
Show
