Output split-editors.gif
Set FontSize 16

Hide
Type "go build -o split-editors ."
Enter
Type "clear"
Enter
Show

Type "./split-editors"
Enter
Sleep 1

Type "Hello, there!"
Sleep 0.5
Tab
Sleep 0.5
Type "Hi!"
Sleep 0.5
Enter
Type "How are you?"
Sleep 0.5
Tab
Sleep 0.5
Ctrl+U
Sleep 0.5
Type "I'm good! Thanks for asking :)"
Sleep .5
Enter
Sleep 0.5
Ctrl+N
Sleep 0.5
Tab@250ms 2
Type "Hello, world!"
Sleep 1

Hide
Escape
Type "rm split-editors"
Enter
