version: "2"
run:
  tests: false
linters:
  enable:
    - bodyclose
    - exhaustive
    - goconst
    - godot
    - gomoddirectives
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
    - wrapcheck
  exclusions:
    rules:
      - text: '(slog|log)\.\w+'
        linters:
          - noctx
      - text: "var-naming"
        linters:
          - revive
      - text: "G705"
        linters:
          - gosec
      - text: "G115"
        linters:
          - gosec
      - text: "os/exec.Command must not be called"
        linters:
          - noctx
    generated: lax
    presets:
      - common-false-positives
  settings:
    exhaustive:
      default-signifies-exhaustive: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
