includes:
  - from_url:
      url: charmbracelet/meta/main/goreleaser-full.yaml

variables:
  main: "./cmd/vhs"
  description: "A tool for recording terminal GIFs"
  github_url: "https://github.com/charmbracelet/vhs"
  maintainer: "Maas Lalani <maas@charm.sh>"
  brew_commit_author_name: "Maas Lalani"
  brew_commit_author_email: "maas@charm.sh"
