# Output examples/settings/set-loop-offset.mp4
Output examples/settings/set-loop-offset.webm
# Output examples/settings/frames/

Output examples/settings/set-loop-offset.gif

# Set LoopOffset 300
Set LoopOffset 99.5%

Type "Betty bought a butter but the bit of butter was bitter."
Sleep 1s
Type " So Betty bought another bit of butter to make the bitter bit of butter, a better bit of butter."
Sleep 2s

