Output "examples/settings/set-corner-radius.gif"
Set FontSize 25
Set Width 600
Set Height 300
Set Padding 20

# You'll probably want a margin if you're
# using CornerRadius.
# Rounded corners without a margin will work,
# but not all output formats support transparency.
# (gif does, mp4 and webm do not)
Set MarginFill "#79B8C3"
Set MarginSize 20

Set CornerRadius 20

Type "I have round corners!"
Sleep 2s