# Source code for the VHS neofetch example.
#
# To run:
#
#     vhs < neofetch.tape

Output examples/neofetch/neofetch.gif
Output examples/neofetch/neofetch.mp4
Output examples/neofetch/neofetch.webm
Output examples/neofetch/frames/

Set TypingSpeed 75ms
Set FontSize 22
Set Width 1300
Set Height 650

Type "neofetch"

Sleep 500ms

Enter

Sleep 2s

Type "Welcome to VHS!"

Sleep 1

Space

Type "A tool for generating terminal GIFs from code."

Sleep 5s
