.PHONY: input write filter choose confirm format spin style demo join commit pick-commit pick-tmux-session customization

input:
	go run input/main.go
write:
	go run write/main.go
filter:
	go run filter/main.go
choose:
	go run choose/main.go
confirm:
	go run confirm/main.go
format:
	go run format/main.go
spin:
	go run spin/main.go
style:
	go run style/main.go
join:
	go run join/main.go

commit:
	go run commit/main.go

pick-commit:
	go run pick-commit/main.go
pick-tmux-session:
	go run pick-tmux-session/main.go
customization:
	go run customization/main.go

demo:
	go run demo/main.go
