.PHONY: input write filter choose format spin

input:
	go run input/main.go
write:
	go run write/main.go
filter:
	go run filter/main.go
choose:
	go run choose/main.go
format:
	go run format/main.go
spin:
	go run spin/main.go
